type Book = {
  id: number
  name: string
  nameFr: string
  chapters: number
}

const books: Book[] = [
  { id: 1, name: 'Genesis', nameFr: 'Genèse', chapters: 50 },
  { id: 2, name: 'Exodus', nameFr: 'Exode', chapters: 40 },
  { id: 3, name: 'Leviticus', nameFr: 'Lévitique', chapters: 27 },
  { id: 4, name: 'Numbers', nameFr: 'Nombres', chapters: 36 },
  { id: 5, name: 'Deuteronomy', nameFr: 'Deutéronome', chapters: 34 },
  { id: 6, name: 'Joshua', nameFr: 'Josué', chapters: 24 },
  { id: 7, name: 'Judges', nameFr: 'Juges', chapters: 21 },
  { id: 8, name: 'Ruth', nameFr: 'Ruth', chapters: 4 },
  { id: 9, name: '1 Samuel', nameFr: '1 Samuel', chapters: 31 },
  { id: 10, name: '2 Samuel', nameFr: '2 Samuel', chapters: 24 },
  { id: 11, name: '1 Kings', nameFr: '1 Rois', chapters: 22 },
  { id: 12, name: '2 Kings', nameFr: '2 Rois', chapters: 25 },
  { id: 13, name: '1 Chronicles', nameFr: '1 Chroniques', chapters: 29 },
  { id: 14, name: '2 Chronicles', nameFr: '2 Chroniques', chapters: 36 },
  { id: 15, name: 'Ezra', nameFr: 'Esdras', chapters: 10 },
  { id: 16, name: 'Nehemiah', nameFr: 'Néhémie', chapters: 13 },
  { id: 17, name: 'Esther', nameFr: 'Esther', chapters: 10 },
  { id: 18, name: 'Job', nameFr: 'Job', chapters: 42 },
  { id: 19, name: 'Psalms', nameFr: 'Psaumes', chapters: 150 },
  { id: 20, name: 'Proverbs', nameFr: 'Proverbes', chapters: 31 },
  { id: 21, name: 'Ecclesiastes', nameFr: 'Ecclésiaste', chapters: 12 },
  { id: 22, name: 'Song of Solomon', nameFr: 'Cantique des Cantiques', chapters: 8 },
  { id: 23, name: 'Isaiah', nameFr: 'Ésaïe', chapters: 66 },
  { id: 24, name: 'Jeremiah', nameFr: 'Jérémie', chapters: 52 },
  { id: 25, name: 'Lamentations', nameFr: 'Lamentation de Jérémie', chapters: 5 },
  { id: 26, name: 'Ezekiel', nameFr: 'Ézéchiel', chapters: 48 },
  { id: 27, name: 'Daniel', nameFr: 'Daniel', chapters: 12 },
  { id: 28, name: 'Hosea', nameFr: 'Osée', chapters: 14 },
  { id: 29, name: 'Joel', nameFr: 'Joël', chapters: 4 },
  { id: 30, name: 'Amos', nameFr: 'Amos', chapters: 9 },
  { id: 31, name: 'Obadiah', nameFr: 'Abdias', chapters: 1 },
  { id: 32, name: 'Jonah', nameFr: 'Jonas', chapters: 4 },
  { id: 33, name: 'Micah', nameFr: 'Michée', chapters: 7 },
  { id: 34, name: 'Nahum', nameFr: 'Nahum', chapters: 3 },
  { id: 35, name: 'Habakkuk', nameFr: 'Habacuc', chapters: 3 },
  { id: 36, name: 'Zephaniah', nameFr: 'Sophonie', chapters: 3 },
  { id: 37, name: 'Haggai', nameFr: 'Aggée', chapters: 2 },
  { id: 38, name: 'Zechariah', nameFr: 'Zacharie', chapters: 14 },
  { id: 39, name: 'Malachi', nameFr: 'Malachie', chapters: 4 },
  { id: 40, name: 'Matthew', nameFr: 'Matthieu', chapters: 28 },
  { id: 41, name: 'Mark', nameFr: 'Marc', chapters: 16 },
  { id: 42, name: 'Luke', nameFr: 'Luc', chapters: 24 },
  { id: 43, name: 'John', nameFr: 'Jean', chapters: 21 },
  { id: 44, name: 'Acts', nameFr: 'Actes', chapters: 28 },
  { id: 45, name: 'Romans', nameFr: 'Romains', chapters: 16 },
  { id: 46, name: '1 Corinthians', nameFr: '1 Corinthiens', chapters: 16 },
  { id: 47, name: '2 Corinthians', nameFr: '2 Corinthiens', chapters: 13 },
  { id: 48, name: 'Galatians', nameFr: 'Galates', chapters: 6 },
  { id: 49, name: 'Ephesians', nameFr: 'Éphésiens', chapters: 6 },
  { id: 50, name: 'Philippians', nameFr: 'Philippiens', chapters: 4 },
  { id: 51, name: 'Colossians', nameFr: 'Colossiens', chapters: 4 },
  { id: 52, name: '1 Thessalonians', nameFr: '1 Thessaloniciens', chapters: 5 },
  { id: 53, name: '2 Thessalonians', nameFr: '2 Thessaloniciens', chapters: 3 },
  { id: 54, name: '1 Timothy', nameFr: '1 Timothée', chapters: 6 },
  { id: 55, name: '2 Timothy', nameFr: '2 Timothée', chapters: 4 },
  { id: 56, name: 'Titus', nameFr: 'Tite', chapters: 3 },
  { id: 57, name: 'Philemon', nameFr: 'Philémon', chapters: 1 },
  { id: 58, name: 'Hebrews', nameFr: 'Hébreux', chapters: 13 },
  { id: 59, name: 'James', nameFr: 'Jacques', chapters: 5 },
  { id: 60, name: '1 Peter', nameFr: '1 Pierre', chapters: 5 },
  { id: 61, name: '2 Peter', nameFr: '2 Pierre', chapters: 3 },
  { id: 62, name: '1 John', nameFr: '1 Jean', chapters: 5 },
  { id: 63, name: '2 John', nameFr: '2 Jean', chapters: 1 },
  { id: 64, name: '3 John', nameFr: '3 Jean', chapters: 1 },
  { id: 65, name: 'Jude', nameFr: 'Jude', chapters: 1 },
  { id: 66, name: 'Revelation', nameFr: 'Apocalypse', chapters: 22 },
]

export default books
